# H2
spring:
  datasource:
    url: "jdbc:h2:mem:productstore-testdb;DB_CLOSE_ON_EXIT=true;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=true;INIT=CREATE SCHEMA IF NOT EXISTS product;"
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
