# Server Configuration
server:
  port: 8080
management:
  server:
    port: 8081

# Application
spring:
  application:
    name: productstore

  # Flyway
  flyway:
    enabled: true
    locations: classpath:/db/migration/{vendor}
    baseline-on-migrate: true
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql

# OpenApi
springdoc:
  api-docs:
    path: /v1/api-docs #/v1/api-docs.yaml
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    groups-order: desc
  cache:
    disabled: true

# Custom Properties
app:
  release-version: 1.0.0
  release-name: PRODUCT-STORE
