services:
  product-store:
    container_name: product-store
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: product-store:latest
    environment:
      - SPRING_PROFILES_ACTIVE=${APP_PROFILES}
      - PG_DB_HOST=${PG_DB_HOST}
      - PG_DB_PORT=${PG_DB_PORT}
      - PG_DB_USER=${PG_DB_USER}
      - PG_DB_PASSWORD=${PG_DB_PASSWORD}
      - APP_PG_DB_NAME=${APP_PG_DB_NAME}
      - APP_PG_DB_SCHEMA=${APP_PG_DB_SCHEMA}
      - APP_PG_DB_USER=${APP_PG_DB_USER}
      - APP_PG_DB_PASSWORD=${APP_PG_DB_PASSWORD}
      - SERVER_PORT=8080
      - MANAGEMENT_SERVER_PORT=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - product-store-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
